# Generated by Django 3.2.5 on 2021-09-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0002_auto_20210925_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirages',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
