# Generated by Django 3.2.5 on 2021-09-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0003_alter_tirages_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tirages',
            new_name='Tirage',
        ),
    ]
