# Generated by Django 3.2.5 on 2021-09-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0005_rename_tirages_tirage_tirage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tirage',
            old_name='date',
            new_name='jour',
        ),
    ]
