# Generated by Django 3.2.5 on 2021-10-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0006_rename_date_tirage_jour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tirage',
            old_name='jour',
            new_name='t_jour',
        ),
        migrations.RenameField(
            model_name='tirage',
            old_name='tirage',
            new_name='t_tirage',
        ),
        migrations.RemoveField(
            model_name='tirage',
            name='id',
        ),
        migrations.AddField(
            model_name='tirage',
            name='t_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
