# Generated by Django 3.2.5 on 2021-10-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0007_auto_20211002_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_tirage', models.CharField(db_column='Tirages', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Tirage',
        ),
    ]
