# Generated by Django 3.2.5 on 2021-10-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0009_alter_testtable_t_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='t_jour',
            field=models.CharField(db_column='Jour', default=1, max_length=300),
            preserve_default=False,
        ),
    ]
