# Generated by Django 3.2.5 on 2021-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0011_alter_testtable_t_tirage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='t_tirage',
            field=models.CharField(db_column='Tirages', max_length=300),
        ),
    ]
