# Generated by Django 3.2.5 on 2021-12-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0012_alter_testtable_t_tirage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestTable',
            new_name='LotoTirage',
        ),
    ]
