# Generated by Django 3.2.5 on 2021-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0013_rename_testtable_lototirage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuromillionTirage',
            fields=[
                ('te_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('te_jour', models.CharField(db_column='Jour', max_length=300)),
                ('te_numeros', models.CharField(db_column='Numeros', max_length=300)),
                ('te_numeros_comp', models.CharField(db_column='Complementaire', max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='lototirage',
            old_name='t_id',
            new_name='tl_id',
        ),
        migrations.RenameField(
            model_name='lototirage',
            old_name='t_jour',
            new_name='tl_jour',
        ),
        migrations.RenameField(
            model_name='lototirage',
            old_name='t_tirage',
            new_name='tl_tirage',
        ),
    ]
